matrix:
  bot:
    mode: APPSERVICE
    username: "smsbot"
    trackMembership: ALL
  client:
  appservice:
    namespaces:
      users:
        - exclusive: true
          regex: "sms_[0-9]{6,15}"
      aliases: []
      rooms: []