matrix:
  bot:
    mode: APPSERVICE
  client:
  appservice:
    asUsername: "smsbot"
    namespaces:
      users:
        - exclusive: true
          regex: "sms_[0-9]{6,15}"
      aliases: []
      rooms: []