version: '3.3'
services:
  matrix-sms-bridge:
    image: net.folivo/matrix-sms-bridge
    volumes:
      - type: bind
        source: ./bridge
        target: /config
      - type: bind
        source: ./kannel/config
        target: /etc/kannel
        read_only: true
      - type: bind
        source: ./kannel/spool
        target: /var/spool/kannel
      - type: bind
        source: ./kannel/log
        target: /var/log/kannel
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    depends_on:
      - neo4j
    environment:
      - CONFIG_LOCATION=/config/application.yml
    networks:
      - local-kannel
    expose:
      - 8080
      - 13013
    restart: on-failure
  neo4j:
    image: neo4j:latest
    volumes:
      - ./neo4j:/data
    environment:
      - NEO4J_AUTH=neo4j/secret
    networks:
      - local-kannel
    expose:
      - 7687
    ports:
      - 7474:7474
  matrix-synapse:
    image: matrixdotorg/synapse:latest
    volumes:
      - type: bind
        source: ./synapse
        target: /data
    environment:
      - SYNAPSE_REPORT_STATS=false
      - UID=1000
      - GID=1000
    depends_on:
      - matrix-sms-bridge
    networks:
      - local-kannel
    ports:
      - 8008:8008

networks:
  local-kannel: